#!/usr/bin/env python3

import colors as c
import time as t

count_length = 0.387

snake = '''

                                                              
                     ,--.                      ,--.           
  .--.--.          ,--.'|   ,---,          ,--/  /|    ,---,. 
 /  /    '.    ,--,:  : |  '  .' \      ,---,': / '  ,'  .' | 
|  :  /`. / ,`--.'`|  ' : /  ;    '.    :   : '/ / ,---.'   | 
;  |  |--`  |   :  :  | |:  :       \   |   '   ,  |   |   .' 
|  :  ;_    :   |   \ | ::  |   /\   \  '   |  /   :   :  |-, 
 \  \    `. |   : '  '; ||  :  ' ;.   : |   ;  ;   :   |  ;/| 
  `----.   \'   ' ;.    ;|  |  ;/  \   \:   '   \  |   :   .' 
  __ \  \  ||   | | \   |'  :  | \  \ ,'|   |    ' |   |  |-, 
 /  /`--'  /'   : |  ; .'|  |  '  '--'  '   : |.  \'   :  ;/| 
'--'.     / |   | '`--'  |  :  :        |   | '_\.'|   |    \ 
  `--'---'  '   : |      |  | ,'        '   : |    |   :   .' 
            ;   |.'      `--''          ;   |,'    |   | ,'   
            '---'                       '---'      `----'     
                                                             

'''

while True:

c.clear_screen()

for verse in range(5):

    for badger in range(11):
        print(c.magenta + 'Badgers!'+ c.reset)
        t.sleep(count_length)

    if verse < 4:
        for mushroom in range(2):
            print(c.red + 'Mushroom!' + c.reset)
            t.sleep(count_length * 2)

print(c.yellow + snake + c.reset)
t.sleep(count_length * 2)
c.clear_screen()

















