#!/usr/bin/env python3

import colors as c 

print(c.clear)
print(c.red + '''

Who would cross the Bridge Of Death
Must answer me these questions three
'Ere me need pizza =^.^= 

''' +  c.reset)

    

name = input(c.magenta + 'What is your name ?!? --> ' + c.reset).lower().strip()
quest = input(c.red + 'What u quest? --> ' + c.reset)
if name in  ['lancelot', "galahad"]: 
    color = input(c.cyan + 'What is thou fav colour? --> ' + c.reset)
    color = input(c.yellow + 'What is a apple? --> ' + c.reset)





