#!/usr/bin/env python3

import colors as c

print(c.clear)

print(c.magenta  +'What is your name?')








name = input(c.cyan  +'--> ' +c.yellow + '  ')
print(c.red +'Nice to meet you, ' + name + '!')



