#!/usr/bin/env python3 

import colors as c

print('Having feelings again? Well, this is the right place for you.') 
input('--> ' + c.green)
print('Well, calm down. Take five deep breathes, and remeber that you are loved.')












