#!/usr/bin/env python3

import colors as c
print(c.clear)
print(c.red + 'Hi, What is your name' + c.reset)

name = input(c.yellow + '>' + c.reset)

print(c.magenta + 'Well, nice to meet you, ' +  name)









































